'use client';
import { useMemo, useState } from 'react';
import AdminTabs from './AdminTabs';
import AdminModal from './AdminModal';
import { parseCsv } from '../../lib/csv/parse';
import { toLeagueDateTimeInput } from '../../lib/formatters';
import { Game, GameStat, Player, Season, Tab, Team, Trade } from './types';

export default function AdminDashboardShell({data,role,testMode,runAction,refresh}:{data:any,role:any,testMode:boolean,runAction:any,refresh:any}){
const [active,setActive]=useState<Tab>('dashboard');
const [seasonFilter,setSeasonFilter]=useState<string>(data.currentSeasonId||data.seasons?.[0]?.id||'all');
const [modal,setModal]=useState<any>(null); const [pending,setPending]=useState(false); const [err,setErr]=useState<string|null>(null);
const seasons:Season[]=data.seasons||[]; const teams:Team[]=data.teams||[]; const players:Player[]=data.players||[]; const games:Game[]=data.games||[]; const trades:Trade[]=data.trades||[]; const gameStats:GameStat[]=data.gameStats||[];
const seasonTeams=seasonFilter==='all'?teams:teams.filter(t=>t.season_id===seasonFilter); const seasonPlayers=seasonFilter==='all'?players:players.filter(p=>p.season_id===seasonFilter); const seasonGames=seasonFilter==='all'?games:games.filter(g=>g.season_id===seasonFilter);
const unassigned=seasonPlayers.filter(p=>!p.team_id).length; const upcoming=seasonGames.filter(g=>new Date(g.scheduled_at).getTime()>Date.now()).length; const pendingTrades=trades.filter(t=>t.status.includes('proposed')||t.status.includes('accepted')).length;
const recentFinal=[...seasonGames].filter(g=>g.status==='FINAL').sort((a,b)=>+new Date(b.scheduled_at)-+new Date(a.scheduled_at)).slice(0,5);

const submit=async(action:string,payload:any)=>{setPending(true);setErr(null);const ok=await runAction(action,payload);setPending(false);if(!ok){setErr('Save failed');return false;} await refresh(); setModal(null); return true};
const [csvRows,setCsvRows]=useState<any[]>([]); const [csvKind,setCsvKind]=useState<'players'|'games'>('players'); const [targetSeason,setTargetSeason]=useState(seasonFilter==='all'?(data.currentSeasonId||''):seasonFilter);

const preloadStats=(gameId:string)=>gameStats.filter((s:any)=>s.game_id===gameId);

return <main><h1>League Operations Dashboard</h1><p className='muted'>Role: {role}{testMode?' (test mode active)':''}</p>
<div className='form-field'><label>Working Season</label><select value={seasonFilter} onChange={e=>setSeasonFilter(e.target.value)}><option value='all'>All</option>{seasons.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div>
<AdminTabs active={active} onChange={setActive}/>{err&&<p>{err}</p>}
{active==='dashboard'&&<section className='card'><h2>Dashboard Home</h2><p><strong>Current season:</strong> {(seasons.find(s=>s.id===seasonFilter)||seasons.find((s:any)=>s.id===data.currentSeasonId)||{name:'All'}).name}</p><p>Teams {seasonTeams.length} · Players {seasonPlayers.length} · Unassigned {unassigned} · Upcoming games {upcoming} · Pending trades {pendingTrades}</p><div className='button-row'><button onClick={()=>setModal({type:'player'})}>Add Player</button><button onClick={()=>{setCsvKind('players');setModal({type:'csv'})}}>Import Players</button><button onClick={()=>{setCsvKind('games');setModal({type:'csv'})}}>Import Schedule</button><button onClick={()=>setModal({type:'game'})}>Add Game</button><button onClick={()=>setActive('scores')}>Enter Scores</button><button onClick={()=>setActive('dfs')}>DFS Admin</button></div><h3>Recent completed games</h3>{recentFinal.map(g=><p key={g.id}>{g.home_score}-{g.away_score} · {new Date(g.scheduled_at).toLocaleString()}</p>)}</section>}
{active==='players'&&<section className='card'><div className='section-header-row'><h2>Players</h2><div><button onClick={()=>setModal({type:'player'})}>Add Player</button><button onClick={()=>{setCsvKind('players');setModal({type:'csv'})}}>Import Players</button></div></div><div className='responsive-table'><table className='table'><thead><tr><th>Name</th><th>Team</th><th>Pos</th><th></th></tr></thead><tbody>{seasonPlayers.map(p=><tr key={p.id}><td>{p.name}</td><td>{teams.find(t=>t.id===p.team_id)?.name||'Unassigned'}</td><td>{p.position||'-'}</td><td><button onClick={()=>setModal({type:'player',item:p})}>Edit</button></td></tr>)}</tbody></table></div></section>}
{active==='games'&&<section className='card'><div className='section-header-row'><h2>Games</h2><div><button onClick={()=>setModal({type:'game'})}>Add Game</button><button onClick={()=>{setCsvKind('games');setModal({type:'csv'})}}>Import Schedule</button></div></div><div className='responsive-table'><table className='table'><thead><tr><th>Date</th><th>Matchup</th><th>Status</th><th></th></tr></thead><tbody>{seasonGames.map(g=><tr key={g.id}><td>{new Date(g.scheduled_at).toLocaleString()}</td><td>{teams.find(t=>t.id===g.home_team)?.name} vs {teams.find(t=>t.id===g.away_team)?.name}</td><td>{g.status}</td><td><button onClick={()=>setModal({type:'game',item:g})}>Edit</button></td></tr>)}</tbody></table></div></section>}
{active==='scores'&&<section className='card'><h2>Scores</h2>{seasonGames.map(g=><div key={g.id} className='list-card compact'><p>{teams.find(t=>t.id===g.home_team)?.name} {g.home_score}-{g.away_score} {teams.find(t=>t.id===g.away_team)?.name}</p><button onClick={()=>setModal({type:'score',item:g})}>{g.status==='FINAL'?'Update Score':'Enter Score'}</button></div>)}</section>}
{active==='registrations'&&<section className='card'><h2>Registrations</h2><p className='muted'>Registrations tab is reachable and active.</p></section>}
{active==='trades'&&<section className='card'><h2>Trade Review</h2><p>Pending {pendingTrades}</p></section>}
{active==='dfs'&&<section className='card'><h2>DFS Admin Panel</h2><button onClick={()=>runAction('dfs_auto_generate_weekly_default',{})}>Generate Default Slate</button></section>}

<AdminModal open={!!modal} onClose={()=>setModal(null)} title={modal?.type==='csv'?'CSV Import':modal?.type==='score'?'Score Entry':'Edit'} footer={<><button onClick={()=>setModal(null)}>Cancel</button></>}>
{modal?.type==='player'&&(()=>{const i=modal.item||{}; const [f,setF]=[modal.form||{id:i.id||'',name:i.name||'',position:i.position||'',team_id:i.team_id||'',season_id:i.season_id||targetSeason},(v:any)=>setModal((m:any)=>({...m,form:{...(m.form||{id:i.id||'',name:i.name||'',position:i.position||'',team_id:i.team_id||'',season_id:i.season_id||targetSeason}),...v}}))]; return <div className='form-grid'><input placeholder='Name' value={f.name} onChange={e=>setF({name:e.target.value})}/><select value={f.team_id} onChange={e=>setF({team_id:e.target.value})}><option value=''>Unassigned</option>{seasonTeams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><button disabled={pending} onClick={()=>submit(f.id?'player_update':'player_create',f)}>Save</button></div>})()}
{modal?.type==='game'&&(()=>{const i=modal.item||{}; const f=modal.form||{id:i.id||'',season_id:i.season_id||targetSeason,home_team:i.home_team||'',away_team:i.away_team||'',scheduled_at:toLeagueDateTimeInput(i.scheduled_at)||'',status:i.status||'SCHEDULED'}; const setF=(v:any)=>setModal((m:any)=>({...m,form:{...f,...v}})); return <div className='form-grid'><select value={f.home_team} onChange={e=>setF({home_team:e.target.value})}>{seasonTeams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><select value={f.away_team} onChange={e=>setF({away_team:e.target.value})}>{seasonTeams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><input type='datetime-local' value={f.scheduled_at} onChange={e=>setF({scheduled_at:e.target.value})}/><button onClick={()=>submit(f.id?'game_update':'game_create',{...f,scheduled_at:new Date(f.scheduled_at).toISOString()})}>Save</button></div>})()}
{modal?.type==='csv'&&<div><label>Target Season</label><select value={targetSeason} onChange={e=>setTargetSeason(e.target.value)}>{seasons.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input type='file' accept='.csv' onChange={async e=>{const file=e.target.files?.[0]; if(!file)return; const {headers,rows}=parseCsv(await file.text()); const norm=headers.map(h=>h.trim().toLowerCase()); const objs=rows.map(r=>Object.fromEntries(r.map((v,i)=>[norm[i],v]))); setCsvRows(objs);}}/><p>Preview rows: {csvRows.length}</p><button onClick={()=>submit(csvKind==='players'?'import_players_csv':'import_games_csv',{rows:csvRows,target_season_id:targetSeason,dry_run:true})}>Dry Run</button><button onClick={()=>submit(csvKind==='players'?'import_players_csv':'import_games_csv',{rows:csvRows,target_season_id:targetSeason})}>Import</button></div>}
{modal?.type==='score'&&(()=>{const g=modal.item; const existing=preloadStats(g.id); const roster=players.filter(p=>p.team_id===g.home_team||p.team_id===g.away_team); const rows=(modal.rows|| (existing.length?existing:roster.map(p=>({player_id:p.id,team_id:p.team_id,position:p.position,games_played:0,goals:0,assists:0,goals_against:0})))); const setRows=(r:any)=>setModal((m:any)=>({...m,rows:r})); const hs=modal.homeScore??String(g.home_score||0); const as=modal.awayScore??String(g.away_score||0); return <div><div className='button-row'><button onClick={()=>setRows(rows.map((r:any)=>({...r,games_played:1})))}>Mark all GP=1</button><button onClick={()=>setRows(rows.map((r:any)=>({...r,games_played:0,goals:0,assists:0,goals_against:0})))}>Clear stats</button><button onClick={()=>setRows(rows.map((r:any)=>String(r.position||'').toLowerCase().includes('goal')?{...r,goals_against:r.team_id===g.home_team?Number(as):Number(hs)}:r))}>Set goalie GA from score</button></div><input value={hs} onChange={e=>setModal((m:any)=>({...m,homeScore:e.target.value}))}/><input value={as} onChange={e=>setModal((m:any)=>({...m,awayScore:e.target.value}))}/><div className='responsive-table'><table className='table'><tbody>{rows.map((r:any,idx:number)=><tr key={r.player_id}><td>{players.find(p=>p.id===r.player_id)?.name}</td><td><input value={r.games_played} onChange={e=>{const n=[...rows];n[idx]={...r,games_played:Number(e.target.value)};setRows(n);}}/></td><td><input value={r.goals} onChange={e=>{const n=[...rows];n[idx]={...r,goals:Number(e.target.value)};setRows(n);}}/></td><td><input value={r.assists} onChange={e=>{const n=[...rows];n[idx]={...r,assists:Number(e.target.value)};setRows(n);}}/></td><td><input value={r.goals_against} onChange={e=>{const n=[...rows];n[idx]={...r,goals_against:Number(e.target.value)};setRows(n);}}/></td></tr>)}</tbody></table></div><button onClick={()=>submit('game_score_submit',{gameId:g.id,homeScore:Number(hs),awayScore:Number(as),stats:rows})}>Save Score</button></div>})()}
</AdminModal>
</main>
}
