'use client';
function sortPlayers(rows:any[], players:any[]){
 return [...rows].sort((a,b)=>{const pa=players.find((p:any)=>p.id===a.player_id)||{};const pb=players.find((p:any)=>p.id===b.player_id)||{};const ja=Number(pa.jersey||9999), jb=Number(pb.jersey||9999); if(ja!==jb)return ja-jb; return String(pa.name||'').localeCompare(String(pb.name||''));});
}
export default function ScoreEntryModal({game,teams,players,homeScore,awayScore,setHomeScore,setAwayScore,rows,setRows,onSave}:any){
 const homeRows=sortPlayers(rows.filter((r:any)=>players.find((p:any)=>p.id===r.player_id)?.team_id===game.home_team),players);
 const awayRows=sortPlayers(rows.filter((r:any)=>players.find((p:any)=>p.id===r.player_id)?.team_id===game.away_team),players);
 const render=(list:any[],teamId:string)=> <table className='table'><thead><tr><th>#</th><th>Player</th><th>Pos</th><th>GP</th><th>G</th><th>A</th><th>GA</th></tr></thead><tbody>{list.map((r:any)=>{const p=players.find((x:any)=>x.id===r.player_id)||{}; const isGoalie=String(p.position||'').toLowerCase().includes('goal'); return <tr key={r.player_id}><td>{p.jersey??'-'}</td><td>{p.name}</td><td>{p.position||'-'}</td><td><input type='checkbox' checked={Number(r.games_played||0)>0} onChange={e=>setRows(rows.map((x:any)=>x.player_id===r.player_id?{...x,games_played:e.target.checked?1:0}:x))}/></td><td><input value={r.goals} onChange={e=>setRows(rows.map((x:any)=>x.player_id===r.player_id?{...x,goals:Number(e.target.value||0)}:x))}/></td><td><input value={r.assists} onChange={e=>setRows(rows.map((x:any)=>x.player_id===r.player_id?{...x,assists:Number(e.target.value||0)}:x))}/></td><td>{isGoalie?<input value={r.goals_against} onChange={e=>setRows(rows.map((x:any)=>x.player_id===r.player_id?{...x,goals_against:Number(e.target.value||0)}:x))}/>:<span>-</span>}</td></tr>})}</tbody></table>;
 return <div><div className='button-row'><button onClick={()=>setRows(rows.map((r:any)=>({...r,games_played:1})))}>Mark all GP</button><button onClick={()=>setRows(rows.map((r:any)=>({...r,games_played:0,goals:0,assists:0,goals_against:0})))}>Clear all</button></div><div className='scoresheet-grid'><div><h3>{teams.find((t:any)=>t.id===game.home_team)?.name}</h3><label>Home Score</label><input value={homeScore} onChange={e=>setHomeScore(e.target.value)}/>{render(homeRows,game.home_team)}</div><div><h3>{teams.find((t:any)=>t.id===game.away_team)?.name}</h3><label>Away Score</label><input value={awayScore} onChange={e=>setAwayScore(e.target.value)}/>{render(awayRows,game.away_team)}</div></div><button onClick={onSave}>Save Final</button></div>
}
